### ISSUE TITLE
(Modified) Crash on trying to pick up something like Ground Storage

### ISSUE THREAD

**Issue by Craluminum2413** [copygirl/CarryCapacity#18]
![image](https://user-images.githubusercontent.com/69315569/154989785-36569f80-e5d0-4900-aeb8-5c2fdf120500.png)
```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.16.4-rc.2 (Unstable)
Loaded Mods: ancienttools@1.3.6, cralutweaks@1.0.0, qptech@1.7.3, game@1.16.4-rc.2, carrycapacity@0.6.5-rc.2, creative@1.16.4-rc.2, survival@1.16.4-rc.2
02/21/2022 18:00:24: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at CarryCapacity.CarriedBlockExtensions.IsCarryable(Block block, CarrySlot slot)
   at CarryCapacity.CarriedBlock.PickUp(IWorldAccessor world, BlockPos pos, CarrySlot slot, Boolean checkIsCarryable)
   at CarryCapacity.CarriedBlockExtensions.Carry(Entity entity, BlockPos pos, CarrySlot slot, Boolean checkIsCarryable)
   at CarryCapacity.Common.CarryHandler.OnGameTick(Single deltaTime)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _25hCbD9BEFkP69yUQhdpPQgkOvd._qqcop0mvH9ZoRMTDJIwGb6fcyPM(Single )
   at _bjnBWlJotnHiR69aw1flHb4F023._U6WbyQ4am861wMSz04lHr6bdWYyA(Single )
   at _bjnBWlJotnHiR69aw1flHb4F023._PeYLgU97COZFmBgbuLznjIwJUOS(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at _As7FGAmUC8gaKIkRNk2zuk1jlJ._zleiWFUbDyAE8J9zHf00bJUUlQr(_M5s9po0jOCy75F2Bz2DU6XdfcDb , String[] )
   at _f8y3Fmmhb3dxIjBj0LM71AeVhBG._zleiWFUbDyAE8J9zHf00bJUUlQr(ThreadStart )
```

**Comment by copygirl** [comment]
Ground Storage has no item associated with it, so it can't really reasonably exist in an inventory. The item is required for running code for placing the carried block back down. Technically, the call to `Block.OnPickBlock()` returns `null` and therefore some code later on fails with this exception.
